# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/jaysmentor_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=MySuperSecretKeyForJWTTokenMySuperSecretKeyForJWTToken
jwt.expiration-ms=86400000
# Static image path (frontend public path)
app.mentor.image.path=/assets/jay_profile.png

# Local absolute path on your dev machine (for tooling if needed)
app.mentor.image.local-path=C:\\Users\\admin\\Desktop\\Jay-s-Mentor\\frontend\\public\\assets\\jay_profile.png

